-- 코드를 입력하세요
SELECT I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, round(AVG(R.REVIEW_SCORE),2) AS SCORE
FROM REST_INFO I, REST_REVIEW R
WHERE I.REST_ID = R.REST_ID AND SUBSTR(I.ADDRESS, 1, 2) = '서울'
GROUP BY r.REST_ID
ORDER BY SCORE DESC, I.FAVORITES DESC;

# SELECT * FROM REST_INFO;